# Site settings
title: Atrey Desai
author:
  name: Atrey Desai
description: "Research, personal projects, and more!"
remote_theme: murraco/jekyll-theme-minimal-resume

#theme-settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://atreydesai.github.io/" # the base hostname & protocol for your site

#user-settings
username: Atrey Desai
user_title: College Freshman & Student Researcher
user_description: I'm a freshman at the University of Maryland, College Park and previously researched at the Reinforcement Learning And Behavior (RLAB) Group under Dr. Michael Littman at Brown University. The group focuses on applying reinforcement learning to real-world robotics and presented at AAAI-22 and RLDM 2022 on the topic. Following the initial presentation, we worked in conjunction with researchers from the End-User RL Robot Programming group at the University of Chicago to further research the area.
email: atreydesai@gmail.com
instagram_username: atreydesai_
linkedin_username: atreydesai
github_username:  atreydesai