# Site settings
title: Atrey Desai
author:
  name: Atrey Desai
description: "Research, personal projects, and more!"
remote_theme: murraco/jekyll-theme-minimal-resume

#theme-settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://atreydesai.github.io/" # the base hostname & protocol for your site

#user-settings
username: Atrey Desai
user_title: Student Researcher
user_description: I'm a freshman at [college] and currently research at the Reinforcement Learning And Behavior (RLAB) Group under Dr. Michael Littman at Brown University. The group focuses on applying reinforcement learning to real-world robotics and presented at AAAI-22 and RLDM 2022 on the topic. Currently, we are collaborating with researchers from the End-User RL Robot Programming group at the University of Chicago.
email: atreydesai@gmail.com
instagram_username: atrey_desai
linkedin_username: atreydesai
github_username:  atreydesai